"""
02_graph.py — Identity graph visualisation page.

Renders the pyvis HTML graph generated by GraphBuilder.
Falls back to mock data if no run has been executed.

Architecture position: reads graph data from Neo4j or session state.
"""
import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))

import streamlit as st
import streamlit.components.v1 as components
from graph.neo4j_manager import test_connection, fetch_graph_for_run
from graph.visualizer import generate_pyvis_html

st.title("🕸 Identity Graph")

# Check Neo4j connection
neo4j_ok = test_connection()
st.sidebar.markdown("### Neo4j Status")
if neo4j_ok:
    st.sidebar.success("✅ Neo4j Connected")
else:
    st.sidebar.error("❌ Neo4j Offline — run: docker compose up -d neo4j")

# Fetch graph data
run_id = st.session_state.get("run_id", None)
if run_id and neo4j_ok:
    graph_data = fetch_graph_for_run(run_id)
    nodes, edges = graph_data["nodes"], graph_data["edges"]
    st.caption(f"Showing {len(nodes)} nodes, {len(edges)} relationships")
else:
    # Use mock data for Phase 1 demo
    from mock_responses import MOCK_DEEP_DIVE_RESULTS
    nodes = MOCK_DEEP_DIVE_RESULTS["entities"]
    edges = MOCK_DEEP_DIVE_RESULTS["relationships"]
    st.info("Showing mock graph data. Run a research target first for live graph.")

html = generate_pyvis_html(nodes, edges)
components.html(html, height=520, scrolling=False)

# Legend
st.markdown("#### Node Legend")
cols = st.columns(6)
legend = [
    ("Person", "#2471A3"), ("Organization", "#1E8449"), ("Fund", "#CA6F1E"),
    ("Filing", "#C0392B"), ("Event", "#7D3C98"), ("Location", "#17A589"),
]
for col, (label, color) in zip(cols, legend):
    col.markdown(f'<span style="color:{color}">●</span> {label}', unsafe_allow_html=True)
